- name: Проброс GPU
  ansible.builtin.include_role:
    name: proxmox
    tasks_from: lxc_gpu_passthru

- name: Установка Docker
  ansible.builtin.include_role:
    name: docker

- name: Установка Nvidia CTK
  ansible.builtin.include_role:
    name: nvidia
    tasks_from: container_toolkit
  vars:
    nvidia_ctk_no_cgroups: "true"

- name: Конвертируем в шаблон
  ansible.builtin.include_role:
    name: proxmox
    tasks_from: lxc_convert_to_template