#!/bin/bash
export ANSIBLE_DIR=$(dirname "$(readlink -f "${BASH_SOURCE}")")
export ANSIBLE_CONFIG=${ANSIBLE_DIR}/ansible.cfg
source ${ANSIBLE_DIR}/.venv/bin/activate
source ${ANSIBLE_DIR}/.secrets.env
