proxmox_node        : "{{ default(lookup('env', 'PROXMOX_NODE')) }}"
proxmox_api_host    : "{{ default(lookup('env', 'PROXMOX_API_HOST')) }}"
proxmox_api_user    : "{{ default(lookup('env', 'PROXMOX_USERNAME')) }}"
proxmox_api_pass    : "{{ default(lookup('env', 'PROXMOX_PASSWORD')) }}"

proxmox_wait_sec  : 15    # Время ожидания запуска/остановки VM и LXC

# Настройки пользователя и роли для Terraform
proxmox_terraform_user: "terraform@pve"
proxmox_terraform_role:
  name: Terraform
  privileges: 
    - "Datastore.AllocateSpace" 
    - "Datastore.Audit" 
    - "Pool.Allocate"
    - "Sys.Audit" 
    - "Sys.Console" 
    - "Sys.Modify"
    - "VM.Allocate"
    - "VM.Audit"
    - "VM.Clone"
    - "VM.Config.CDROM"
    - "VM.Config.Cloudinit" 
    - "VM.Config.CPU" 
    - "VM.Config.Disk"
    - "VM.Config.HWType"
    - "VM.Config.Memory"
    - "VM.Config.Network"
    - "VM.Config.Options"
    - "VM.Migrate"
    - "VM.Monitor"
    - "VM.PowerMgmt"
    - "SDN.Use"
