- name: Deploy Jupyter Notebook (docker via compose)
  vars: # noqa jinja[spacing]
    _image     : "{{ x_image   | default('quay.io/jupyter/pytorch-notebook:cuda12-ubuntu-24.04') }}"
    _port      : "{{ x_port    | default('8888') }}"
    _volume    : "{{ x_volume  | default('./notebooks') }}"
    _gen_cert  : "{{ x_gen_cert| default(false) }}"
    _user      : "{{ x_user    | default(ansbile_user_id) }}"
  block:
    - ansible.builtin.include_role: # noqa name[missing]
        name: compose_app           # noqa yaml[indentation]
      vars:
        compose_app_name: jupyter
        compose_app_user: "{{ _user }}"
        compose_app_yml: |
          version: '3.8'
          services:
            jupyter:
              image: {{ _image }}
              ports:
                - "{{ _port }}:8888"
              volumes:
                - {{ _volume }}:/home/jovyan/work
              command: start-notebook.sh --NotebookApp.token=''
              environment:
                - RESTARTABLE=yes
                - GEN_CERT={{ _gen_cert }}
