---
# Данный плейбук только для deb-систем

- name: Defiane DEB arch
  shell: dpkg --print-architecture
  register: _deb_arch

- name: Define os codename
  shell: . /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}"
  register: _os_codename

- name: Ensure pre-requisites are installed
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Create directory for Docker GPG keyring
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'


- name: Download and install Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

# Добавляем репозиторий Docker в источники APT
- name: Add Docker repository to Apt sources
  blockinfile:
    path: /etc/apt/sources.list.d/docker.list
    create: true
    block: |
      deb [arch={{ _deb_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ distro_map[ansible_distribution] }} {{ _os_codename.stdout }} stable
    marker: "# {mark} Ansible managed block for Docker repo"
  vars:
    distro_map:
      Linux Mint: ubuntu
      Ubuntu:     ubuntu
      Debian:     debian

- name: Update apt sources
  apt:
    update_cache: yes

- name: Install Docker Engine and related packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - docker-compose-plugin
    state: present

- name: Test Docker installation
  command: docker run hello-world
  register: docker_test
  failed_when: docker_test.rc != 0

- name: Enable Docker to start at boot
  systemd:
    name: docker
    enabled: true
    state: started