---
- block: # Установка драйверов Nvidia на Debian

  - name: Add non-free repo in sources.list
    replace:
      path: /etc/apt/sources.list
      regexp: '^(deb .* {{ ansible_distribution_release }} main).*$'
      replace: '\1 contrib non-free non-free-firmware'
    register: res

  - name: Update apt cache
    apt:
      update_cache: yes
    when: res.changed

  - name: Install nvidia-driver
    apt:
      name:
        - nvidia-driver

  when: ansible_distribution == "Debian"
  
  

  

  