---
# Данный плейбук только для deb-систем
- name: Initialization variables
  ansible.builtin.set_fact:
    _username: "{{ username | default(ansible_user_id) }}"
    _package_req:
      - ca-certificates
      - curl
      - gnupg
    _package:       
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - docker-compose-plugin

- name: Defiane DEB arch
  ansible.builtin.command: |
    dpkg --print-architecture
  changed_when: false
  register: _deb_arch

- name: Define os codename
  ansible.builtin.shell: |
    source /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}"
  args:
    executable: /bin/bash  
  changed_when: false
  register: _os_codename

- name: Ensure pre-requisites are installed
  ansible.builtin.apt:
    name: "{{ _package_req }}" 
    state: present
  become: yes

- name: Create directory for Docker GPG keyring
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download and install Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: yes

# Добавляем репозиторий Docker в источники APT
- name: Add Docker repository to Apt sources
  ansible.builtin.blockinfile:
    path: /etc/apt/sources.list.d/docker.list
    create: true
    block: |
      deb [arch={{ _deb_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ distro_map[ansible_distribution] }} {{ _os_codename.stdout }} stable
    marker: "# {mark} Ansible managed block for Docker repo"
    mode: '0644'
  vars:
    distro_map:
      Linux Mint: ubuntu
      Ubuntu:     ubuntu
      Debian:     debian
  register: _source_update
  become: yes

- name: Update apt sources
  ansible.builtin.apt:
    update_cache: yes
  when: _source_update is changed
  become: yes

- name: Install Docker Engine and related packages
  ansible.builtin.apt:
    name: "{{ _package }}"
    state: present
  become: yes

- name: Enable Docker to start at boot
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  become: yes

- name: Add user to the docker group
  ansible.builtin.user:
    name: "{{ _username }}"
    groups: docker
    append: yes
  become: yes

- name: Test Docker installation
  ansible.builtin.command: docker run hello-world
  register: _docker_test
  changed_when: false
  failed_when: _docker_test.rc != 0
