---
# Вход:  username
# Выход: home_dir
- name: Get home dir for user {{ _username }}
  ansible.builtin.shell: |
    set -o pipefail ; getent passwd {{ _username }} | awk -F: '{print $6}'
  args:
    executable: /bin/bash
  vars:
    _username: "{{ username | default(ansible_user_id) }}"
  changed_when: false
  register: _home_dir

- name: Set var home_dir
  ansible.builtin.set_fact:
    home_dir: "{{ _home_dir.stdout }}"