---
# Возвращает параметры указанного пользователя (по умолчанию - ansible_user_id), такие как:

- name: Initialization variables
  ansible.builtin.set_fact:
    _username: "{{ username | default(ansible_user_id) }}"

- name: Get home dir for user "{{ _username }}"
  ansible.builtin.shell: |
    set -o pipefail ; getent passwd {{ _username }} | awk -F: '{print $6}'
  args:
    executable: /bin/bash
  changed_when: false
  register: _home_dir

- name: Set output variable get_userinfo
  ansible.builtin.set_fact:
    get_userinfo: 
      home_dir: "{{ _home_dir.stdout }}"

- name: Debug
  ansible.builtin.debug:
    var: get_userinfo
    verbosity: 1
