---
# Установка и настройка Terraform (используя зеркало Яндекса)

- name: Initialization variables
  ansible.builtin.set_fact: # noqa jinja[spacing]
    x_path      : "{{ terraform_path   | default('/usr/local/bin') }}"
    x_repo      : "{{ terraform_repo   | default('https://hashicorp-releases.yandexcloud.net/terraform') }}"
    x_arch      : "{{ terraform_arch   | default('linux_amd64') }}"
    x_ver       : "{{ terraform_ver    | default('1.11.3') }}"
    x_user      : "{{ terraform_user   | default(ansiblex_user_id) }}"
    x_mirror    : "{{ terraform_mirror | default('https://terraform-mirror.yandexcloud.net/') }}"

- name: Install required
  ansible.builtin.apt:
    name: jq
  become: yes

- name: Check terraform install and version
  ansible.builtin.shell: |
    set -o pipefail ; terraform version -json | jq -r '.terraformx_version'
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false
  register: o_cur_ver

- name: Debug
  ansible.builtin.debug:
    msg: "{{ o_cur_ver.stdout }} != {{ x_ver }} =>> {{ o_cur_ver.stdout != x_ver }}"
    verbosity: 1

- name: Install Terraform
  tags: [ terraform, install ]
  when: o_cur_ver is failed or o_cur_ver.stdout != x_ver
  block: 
    - name: Download hash file
      ansible.builtin.get_url:
        url: "{{ x_repo }}/{{ x_ver }}/terraform_{{ x_ver }}_SHA256SUMS"
        dest: /tmp/terraform_{{ x_ver }}_SHA256SUMS
        mode: 0644

    - name: Get hash sum
      ansible.builtin.shell: |
        set -o pipefail ; grep terraform_{{ x_ver }}_{{ x_arch }}.zip /tmp/terraform_1.11.3_SHA256SUMS | awk '{print $1}'
      args:
        executable: /bin/bash
      changed_when: false
      register: _hash_sum

    - name: Download Terraform binary
      ansible.builtin.get_url:
        url: "{{ x_repo }}/{{ x_ver }}/terraform_{{ x_ver }}_{{ x_arch }}.zip"
        dest: /tmp/terraform_{{ x_ver }}_{{ x_arch }}.zip
        mode: 0644
        checksum: "sha256:{{ _hash_sum.stdout }}"

    - name: Unzip Terraform archive
      ansible.builtin.unarchive:
        src: /tmp/terraform_{{ x_ver }}_{{ x_arch }}.zip
        dest: "{{ x_path }}"
        remote_src: yes
        mode: 0755
      become: yes

    - name: Delete temp file
      ansible.builtin.command:
        "rm /tmp/terraform_{{ x_ver }}*"
      register: _res_deltemp
      changed_when: _res_deltemp not failed

- name: Configure Terraform for user {{ x_user }}
  block: 

  - name: Get userinfo
    ansible.builtin.include_tasks: getx_userinfo.yml
    vars:
      username: "{{ x_user }}"
      

  - name: Install autocomplete
    ansible.builtin.lineinfile:
      path: "{{ getx_userinfo.home_dir }}/.bashrc"
      line: "complete -C {{ x_path }}/terraform terraform"

  - name: Configure Yandex mirror for terraform
    ansible.builtin.copy:
      content: |
        provider_installation {
          networkx_mirror {
            url     = "{{ x_mirror }}"
            include = ["registry.terraform.io/*/*"]
          }
          direct {
            exclude = ["registry.terraform.io/*/*"]
          }
        }
      dest: "{{ getx_userinfo.home_dir }}/.terraformrc"
      mode: 0644