---
# Возвращает параметры указанного пользователя (по умолчанию - ansible_user_id), такие как:

- name: Initialization variables
  ansible.builtin.set_fact:
    x_user: "{{ x_user | default(ansible_user_id) }}"

- name: Get home dir for user "{{ x_user }}"
  ansible.builtin.shell: |
    set -o pipefail ; getent passwd {{ x_user }} | awk -F: '{print $6}'
  args:
    executable: /bin/bash
  changed_when: false
  register: x_home_dir

- name: Set output variable o_userinfo
  ansible.builtin.set_fact:
    o_userinfo: 
      home_dir: "{{ x_home_dir.stdout }}"

- name: Debug
  ansible.builtin.debug:
    var: o_userinfo
    verbosity: 1
