- name: Check exists installed Ollama
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - /usr/local/bin/lib/ollama
    - /usr/bin/lib/ollama
    - /bin/lib/ollama
  register: path_results
  
- name: Install Ollama
  when: path_results.results|selectattr('stat.exists')|list|length = 0 or app_ollama_force
  ansible.builtin.shell:
    set -o pipefail && curl -fsSL https://ollama.com/install.sh | {{ app_ollama_version }} sh
  changed_when: true
