---
- name: Get getent for "{{ terraform_user }}"
  ansible.builtin.getent: 
    database: passwd
    key     : "{{ terraform_user }}"
    split   : ":"

- name: Get home dir
  ansible.builtin.set_fact:
    terraform_home: "{{ getent_passwd[terraform_user][4] }}"

- name: Install autocomplete
  ansible.builtin.lineinfile:
    path: "{{ terraform_home }}/.bashrc"
    line: "complete -C {{ terraform_path }}/terraform terraform"
  when: terraform_autocomplete

- name: Configure mirror for terraform
  ansible.builtin.template:
    src: .terraformrc.j2
    dest: "{{ terraform_home }}/.terraformrc"
    mode: 0644
