---
- name: Download hash file
  ansible.builtin.get_url:
    url   : "{{ terraform_repo }}/{{ terraform_ver }}/terraform_{{ terraform_ver }}_SHA256SUMS"
    dest  : /tmp/terraform_{{ terraform_ver }}_SHA256SUMS
    mode  : 0644

- name: Get hash sum
  ansible.builtin.shell: |
    set -o pipefail ; grep terraform_{{ terraform_ver }}_{{ terraform_arch }}.zip /tmp/terraform_1.11.3_SHA256SUMS | awk '{print $1}'
  args:
    executable: /bin/bash
  changed_when: false
  register: x_hash_sum

- name: Download Terraform binary
  ansible.builtin.get_url:
    url   : "{{ terraform_repo }}/{{ terraform_ver }}/terraform_{{ terraform_ver }}_{{ terraform_arch }}.zip"
    dest  : /tmp/terraform_{{ terraform_ver }}_{{ terraform_arch }}.zip
    mode  : 0644
    checksum: "sha256:{{ x_hash_sum.stdout }}"

- name: Unzip Terraform archive
  ansible.builtin.unarchive:
    src   : /tmp/terraform_{{ terraform_ver }}_{{ terraform_arch }}.zip
    dest  : "{{ terraform_path }}"
    mode  : 0755
    remote_src: yes
  become: yes

- name: Delete temp file
  ansible.builtin.file:
    path  : "/tmp/terraform_{{ terraform_ver }}*"
    state : absent
