---
- name: Get getent for "{{ terraform_user }}"
  ansible.builtin.getent: 
    database: passwd
    key     : "{{ terraform_user }}"
    split   : ":"

- name: Get home dir
  ansible.builtin.set_fact:
    terraform_home: "{{ getent_passwd[terraform_user][4] }}"

- name: Remove files
  ansible.builtin.file:
    path  : "{{ terraform_home }}/{{ item }}"
    state : "absent"
  loop:
    - "{{ terraform_path }}/terraform"
    - "{{ terraform_home }}/.terraform.d"
    - "{{ terraform_home }}/.terraformrc"

- name: Remove autocomplete for user "{{ terraform_user }}"
  ansible.builtin.lineinfile:
    path  : "{{ terraform_home }}/.bashrc"
    line  : "complete -C {{ terraform_path }}/terraform terraform"
    state : "absent"


