---
- name: Загрузка cloud-init образов в Proxmox
  hosts: pve
  become: yes
  gather_facts: no

  tasks:
    - name: Загрузка cloud-init образов в Proxmox по списку
      ansible.builtin.include_tasks: "{{ ans_dir }}/tasks/cloudimage_load.yml"
      vars:
        proxmox_cloudimage_template_vmid: "{{ item.vmid }}"
        proxmox_cloudimage_url: "{{ item.url }}"
      loop: 
        "{{ proxmox_cloudimages }}"
      tags: cloudinit
