---
- name: Configure Proxmox VE
  hosts: proxmox_all_lxc
  become: yes
  vars:
    lxc_mp:
      - 'mp0: /mnt/lab,mp=/mnt/lab'



  tasks:

  - name: Add mount point to LXC config
    ansible.builtin.lineinfile:
      path: /etc/pve/lxc/{{ proxmox_vmid }}.conf
      line: "{{ item }}"
      state: present
    loop:
      - "{{ lxc_mp }}"
    delegate_to: "{{ proxmox_node }}"
    notify: Reboot

  - name: Install docker-ce
    ansible.builtin.import_tasks: tasks/docker_install.yml
    when: "'docker' in proxmox_tags_parsed"

  - name: GPU Passthru
    ansible.builtin.import_tasks: tasks/lxc_gpu_passthru.yml
    when: "'gpu' in proxmox_tags_parsed"



  handlers:

  - name: Reboot
    ansible.builtin.reboot:
      reboot_timeout: 300



  