- name: Install Terraform on Proxmox VE
  hosts: localhost
  vars:
    proxmox_node: pve

    # terraform_proxmox_plugin_dir: "{{ terraform_proxmox_dir }}/.terraform"
    terraform_proxmox_provider_git: https://github.com/Telmate/terraform-provider-proxmox
    terraform_proxmox_provider_ver: "2.9.14"  
    terraform_proxmox_provider_arch: "linux_amd64"  

    # Настройки Proxmox
    terraform_proxmox_user: terraform@pve
    terraform_proxmox_role:
      name: Terraform
      privileges: 
        - "Datastore.AllocateSpace" 
        - "Datastore.Audit" 
        - "Pool.Allocate"
        - "Sys.Audit" 
        - "Sys.Console" 
        - "Sys.Modify"
        - "VM.Allocate"
        - "VM.Audit"
        - "VM.Clone"
        - "VM.Config.CDROM"
        - "VM.Config.Cloudinit" 
        - "VM.Config.CPU" 
        - "VM.Config.Disk"
        - "VM.Config.HWType"
        - "VM.Config.Memory"
        - "VM.Config.Network"
        - "VM.Config.Options"
        - "VM.Migrate"
        - "VM.Monitor"
        - "VM.PowerMgmt"
        - "SDN.Use"

    # Настройки Terraform
    terraform_proxmox_api_url: https://192.168.0.100:8006/api2/json
  
  tasks:

  - name: Install plugin on localhost
    tags: [ localhost, install ]
    block:

    - name: Get home dir
      ansible.builtin.include_tasks:
        tasks/get_home_dir.yml
      
    - name: Set terraform_plugin_dir
      ansible.builtin.set_fact:
        terraform_plugin_dir: "{{ home_dir }}/.terraform.d/plugins/registry.terraform.io/telmate/proxmox/{{ terraform_proxmox_provider_ver }}/{{ terraform_proxmox_provider_arch }}"

    - name: Check provider install
      ansible.builtin.stat: 
        path:   "{{ terraform_plugin_dir }}/terraform-provider-proxmox"
      register: _terraform_proxmox_provider_exists

    - name: Install provider
      when: not _terraform_proxmox_provider_exists.stat.exists
      block:

      - name: Create directory for repo
        ansible.builtin.file: 
          path:   "{{ terraform_plugin_dir }}"
          state:  directory
          mode:   0755
        register: res

      - name: Install required tools
        ansible.builtin.apt:
          name:
            - golang
        become: true

      - name: Clone from git
        ansible.builtin.git:
          repo: "{{ terraform_proxmox_provider_git }}"
          dest: "/tmp/terraform-provider-proxmox"
          version: "v{{ terraform_proxmox_provider_ver }}"
          update: yes
        register: res

      - name: Run the Makefile
        community.general.make:
          chdir: "/tmp/terraform-provider-proxmox"
        when: res is changed

      - name: Create Terraform plugins directory
        ansible.builtin.file: 
          path:   "{{ terraform_plugin_dir }}"
          state:  directory
          mode:   0755

      - name: Copy plugin for Proxmox
        ansible.builtin.copy:
          src:  "/tmp/terraform-provider-proxmox/bin/terraform-provider-proxmox" 
          dest: "{{ terraform_plugin_dir }}"
          mode: 0755

      - name: Delete temp folders
        ansible.builtin.file:
          path: "/tmp/terraform-provider-proxmox"
          state: absent



  - name: Prepare Proxmox VE for Terraform
    tags: [ proxmox, install ]
    delegate_to: proxmox
    block:
    - name: Install required tools on Proxmox server
      ansible.builtin.apt:
        name: libguestfs-tools
        update_cache: yes
        cache_valid_time: 3600

    - name: Configure Proxmox roles
      proxmox_role:
        name: "{{ terraform_proxmox_role.name }}"
        privileges: "{{ terraform_proxmox_role.privileges }}"
        state: present

    - name: Configure Proxmox user accounts
      proxmox_user:
        name: "{{ terraform_proxmox_user }}"
        state: present
      register: _new_user 

    - name: Configure Proxmox ACLs
      proxmox_acl:
        path: /
        roles: [ "{{ terraform_proxmox_role.name }}" ]
        users: [ "{{ terraform_proxmox_user }}" ]
        state: present

    # FIXME: Создание токена для пользователя proxmox и запись его в файл
    # - name: Create Proxmox Token
    #   when: _new_user.changed
    #   ansible.builtin.import_tasks:
    #     tasks/proxmox_user_token.yml

    # - name: Export Environment Variables on Terraform Machine
    #   ansible.builtin.shell: |
    #     echo 'export PM_API_TOKEN_ID="{{ full_token_id }}"' > "{{ playbook_dir }}/keys/terraform"
    #     echo 'export PM_API_TOKEN_SECRET="{{ secret }}"' >> "{{ playbook_dir }}/keys/terraform"
    #   changed_when: false
    #   delegate_to: localhost



